imports_granularity = "Crate"
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
use_field_init_shorthand = true

single_line_if_else_max_width = 90
single_line_let_else_max_width = 90
